### ISSUE TITLE
Minimizer: try to remove transparent module constraints 

### ISSUE THREAD

**Issue by SkySkimmer** [JasonGross/coq-tools#148] opened 2023-03-16 12:50 UTC
Typically
~~~coq
(* lots of stuff *)
Module Type T. 
Parameter x : bla.
End T.

Module M <: T.
Definition x := (something that depends on lots of stuff).
Definition y := 0.
End M.

(* error using M.y and not M.x *)
~~~
has a lot to minimize blocked by the `<:` constraint.

Real world example: https://github.com/coq/coq/pull/16967#issuecomment-1407558776

**Comment by SkySkimmer** [comment] 2023-03-16 15:58
(meanwhile opaque constraints could be turned into Declare Module)

**Comment by JasonGross** [comment] 2023-05-04 20:16
Duplicate of #140

**Closed as not planned by JasonGross** 2023-05-04 20:16 UTC
Labels: minimize more
